// vue/src/components/TodoItem.vue
<template>
  <div class="todo">
    <input
      class="checkbox"
      type="checkbox"
      v-model="todo.done"
      />
    <input
      type="text"
      placeholder="Todo title"
      v-model="todo.title"
      />
    <button
      type="button"
      class="delete-button"
      @click="$emit('delete')"
      >
      X
    </button>
  </div>
</template>

<script>
export default {
  name: 'TodoItem',
  props: {
    todo: {
      type: Object,
      required: true
    }
  }
}
</script>

// react/src/TodoItem.js
function TodoItem({ index, done, title, updateTodo, deleteTodo }) {
  return (
    <div className="todo">
      <input
        className="checkbox"
        type="checkbox"
        checked={done}
        onChange={({ target }) => updateTodo(index, { done: target.checked })}
      />
      <input
        type="text"
        placeholder="Todo title"
        value={title}
        onChange={({ target }) => updateTodo(index, { title: target.value })}
      />
      <button
        type="button"
        className="delete-button"
        onClick={() => deleteTodo(index)}
      >
        X
      </button>
    </div>
  );
}

export default TodoItem;
